---
problem: rayleigh-taylor
gamma: 1.4
kappa: 0.0
mean_molecular_weight: 1.0
eos: ideal
t0: 0.0
tf: 1.0
max_steps: 1000
cfl: 0.3
max_dt: 1.0e-2
log_frequency: 10
output_frequency: 100
levels: [8,8,4]
lowest_level: 8
problem_parameters:
  density_low: 1.0
  density_high: 2.0
  pressure: 2.5
  interface: 0.5
  perturbation: 0.01
  gravity: [0.0, -1.0, 0.0]
coords:
  - [0.0, 0.0, 0.0]
  - [1.0, 1.0, 1.0]
boundaries:
  xlow: periodic
  xhigh: periodic
  ylow: reflecting
  yhigh: reflecting
  zlow: flow
  zhigh: flow
catalyst:
  script:
  implementation: paraview
  implementation_directory:
