---
problem: acoustic-wave
gamma: 1.4
kappa: 1.0
mean_molecular_weight: 1.0
problem_parameters:
  scale: 5
  amplitude: 1e-8
  r0: 1.0
  p0: 1.0
eos: ideal
t0: 0.0
tf: 0.1
max_steps: 300
cfl: 0.5
max_dt: 1.0
log_frequency: 500
output_frequency: 500
levels: [12, 1, 1]
lowest_level: 12
coords:
  - [0.0, 0.0, 0.0]
  - [1.0, 1.0, 1.0]
boundaries:
  xlow: periodic
  xhigh: periodic
  ylow: flow
  yhigh: flow
  zlow: flow
  zhigh: flow
catalyst:
  script: /path
  implementation: paraview
  implementation_directory: /path
